{% set version = "0.1.2.dev0" %}

package:
  name: pyhelp
  version: {{ version }}

source:
  path: ..

requirements:
  host:
    - python ==3.6
    - numpy 1.15.*
    - m2w64-toolchain
    - libpython
  run:
    - python ==3.6
    - numpy
    - matplotlib
    - scipy
    - geopandas
    - xlrd
    - netcdf4
    - h5py
    - pytables
    
about:
  home: https://github.com/cgq-qgc/pyhelp
  license: MIT
  license_file: LICENSE
  doc_url: https://pyhelp.readthedocs.io/
  summary: A Python library for assessing groundwater recharge at the regional scale with the HELP model
  description: |
    PyHELP is an object oriented Python library providing a set of tools
    to estimate spatially distributed groundwater recharge and other
    hydrological components (runoff and evapotranspiration) using
    the HELP ([Hydrologic Evaluation of Landfill Performance]
    (https://www.epa.gov/land-research/hydrologic-evaluation-landfill-performance-help-model))
    model. PyHELP integrates weather data (from grids or stations),
    land conditions defined by a series of GIS maps as well as soil
    and geological material properties into HELP input files.
    PyHELP also processes HELP simulation results and outputs them as
    maps and graphs, including comparisons of simulation results with
    stream hydrographs. PyHELP thus accompanies users through the entire
    workflow from input file assembly to model calibration and to the
    documentation of results. This workflow is based on the method
    originally developed by [Croteau et al. (2011)]
    (https://www.tandfonline.com/doi/abs/10.4296/cwrj3504451)
    to assess spatially distributed groundwater recharge at the regional scale.
extra:
  recipe-maintainers:
    - jnsebgosselin

