{% set version = "0.1.0.dev0" %}

package:
  name: pyhelp
  version: {{ version }}

source:
  path: ..

requirements:
  host:
    - python ==3.6
    - numpy >=1.15
    - m2w64-toolchain
    - libpython
  run:
    - python ==3.6
    - numpy >=1.15

about:
  home: https://github.com/jnsebgosselin/pyhelp
  license: MIT
  license_file: LICENSE
extra:
  recipe-maintainers:
    - jnsebgosselin
