{% set version = "0.1.1.dev0" %}

package:
  name: pyhelp
  version: {{ version }}

source:
  path: ..

requirements:
  host:
    - python ==3.6
    - numpy 1.15.*
    - m2w64-toolchain
    - libpython
  run:
    - python ==3.6
    - numpy
    - matplotlib
    - scipy
    - geopandas
    - xlrd
    - netcdf4
    - h5py
    - pytables
    
about:
  home: https://github.com/cgq-qgc/pyhelp
  license: MIT
  license_file: LICENSE
  doc_url: https://pyhelp.readthedocs.io/
extra:
  recipe-maintainers:
    - jnsebgosselin
