# https://ci.appveyor.com/project/cgq-qgc/pyhelp

# Based on:
# https://github.com/astropy/astropy/blob/master/appveyor.yml
# https://github.com/geopandas/geopandas/blob/master/appveyor.yml
# https://github.com/conda/conda-build/blob/master/appveyor.yml
# https://github.com/NLeSC/mcfly/blob/master/appveyor.yml

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master
    - 0.1.x

skip_commits:
  files:
    - docs/*
    - '**/*.html'
    - '**/*.md'
    - '**/*.png'
    - '**/*.svg'
    - '**/*.jpg'

image:
  - Visual Studio 2019

environment:
  global:
    PYHELP_VERSION: "v0.2.2"

  matrix:
    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7.*"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda38-x64"
      PYTHON_VERSION: "3.8.*"
      PYTHON_ARCH: "64"

platform:
  -x64

skip_branch_with_pr: true

install:
  # Cancel older builds for the same PR.
  # Credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Setup SYS PATH.
  - set "PATH=%PYTHON%;%PYTHON%/Scripts;%PYTHON%/Library/bin;%PATH%"

  # Setup Conda.
  - conda config --set always_yes yes
  - conda update -q conda
  - conda config --set auto_update_conda no
  - conda install pandas scipy h5py=3 matplotlib pip m2w64-toolchain conda-build=3.21.7 setuptools=58
  - python -m pip install codecov pytest pytest-cov

  # Check that we have still the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  # Add mingw-w64 to SYS PATH.
  - set "PATH=%PYTHON%/Library/mingw-w64/bin;%PATH%"

  # Build the HELP3O extension.
  - "%PYTHON%/python.exe setup.py build_ext"

build: false

test_script:
  - python runtests.py

after_test:
  - IF ["%APPVEYOR_PULL_REQUEST_NUMBER%"]==[""] (%PYTHON%/python.exe setup.py sdist bdist_wheel)
  - 7z a -tzip dist/example_pyhelp_%PYHELP_VERSION%.zip example/*.csv example/help_example.py example/CWEEDS/*
  - conda-build recipe --no-test --output-folder dist --python %PYTHON_VERSION%

artifacts:
  - path: 'dist/*.whl'
  - path: 'dist/*.tar.gz'
  - path: 'dist/example_pyhelp_%PYHELP_VERSION%.zip'
  - path: 'dist/win-64/*.tar.bz2'

on_success:
  - codecov

on_finish:
  - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
