# https://ci.appveyor.com/project/cgq-qgc/pyhelp

# Based on:
# https://github.com/astropy/astropy/blob/master/appveyor.yml
# https://github.com/geopandas/geopandas/blob/master/appveyor.yml
# https://github.com/conda/conda-build/blob/master/appveyor.yml
# https://github.com/NLeSC/mcfly/blob/master/appveyor.yml

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  global:
    APPVEYOR_RDP_PASSWORD: "dcca4c4863E30d56c2e0dda6327370b3#"

  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

platform:
  -x64

skip_branch_with_pr: true

install:
  # Cancel older builds for the same PR.
  # Credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  
  # Setup SYS PATH.
  - set "PATH=%PYTHON%;%PYTHON%/Scripts;%PYTHON%/Library/bin;%PATH%"
  
  # Setup Conda.
  - conda config --set always_yes yes
  - conda update -q conda
  - conda config --set auto_update_conda no
  - conda config --add channels conda-forge
  - conda config --set channel_priority true
  - conda install numpy scipy pandas xlrd netcdf4 h5py pytables matplotlib geopandas pytest pytest-mock pytest-cov codecov sphinx m2w64-toolchain conda-build
  
  # Add mingw-w64 to SYS PATH.
  - set "PATH=%PYTHON%/Library/mingw-w64/bin;%PATH%"

  # Build the HELP3O extension.
  - "%PYTHON%/python.exe setup.py build_ext"

build: false

test_script:
  - python runtests.py
  
after_test:
  - "%PYTHON%/python.exe setup.py bdist_wheel"
  - conda-build recipe/.
  - xcopy '"%PYTHON%/conda-bld" "dist/conda-bld" /s /i /e'

artifacts:
  - path: 'dist/*.whl'
  - path: 'dist/conda-bld/win-64/*.tar.bz2'

on_success:
  - codecov

on_finish:
  - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
