# https://ci.appveyor.com/project/jnsebgosselin/pyhelp

# Based on:
# https://github.com/astropy/astropy/blob/master/appveyor.yml
# https://github.com/geopandas/geopandas/blob/master/appveyor.yml

matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:

  global:
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "latest"
    PYTHON_ARCH: "64"
    APPVEYOR_RDP_PASSWORD: "dcca4c4863E30d56c2e0dda6327370b3#"

  matrix:
    - PYTHON_VERSION: "3.6"

platform:
  -x64

skip_branch_with_pr: true

install:
  # cancel older builds for the same PR
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # set up environment
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --add channels conda-forge
  - "conda create --quiet --name tests python=%PYTHON_VERSION% --file requirements.txt --file requirements-dev.txt"
  - "activate tests

build: false

test_script:
  - python runtests.py

on_success:
  - codecov
